# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-05 11:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cam12pr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_x', models.FloatField()),
                ('start_y', models.FloatField()),
                ('start_z', models.FloatField()),
                ('title', models.CharField(max_length=100)),
            ],
        ),
    ]
